<wsdl:definitions name="WSESTServiceImplService"
	targetNamespace="http://impl.services.est.ws.linkpagos.link.com.ar/">
	<wsdl:import
		location="http://200.45.17.36:80/lpservices/ws/ESTSServices?wsdl=WSESTService.wsdl"
		namespace="http://services.est.ws.linkpagos.link.com.ar/">
	</wsdl:import>
	<wsdl:binding name="WSESTServiceImplServiceSoapBinding"
		type="ns1:WSESTService">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="obtenerTiposDocumentos">
			<soap:operation soapAction="" style="document" />
			<wsdl:input name="obtenerTiposDocumentos">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="obtenerTiposDocumentosResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="obtenerDocumentos">
			<soap:operation soapAction="" style="document" />
			<wsdl:input name="obtenerDocumentos">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="obtenerDocumentosResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="obtenerODEs">
			<soap:operation soapAction="" style="document" />
			<wsdl:input name="obtenerODEs">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="obtenerODEsResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="generarODE">
			<soap:operation soapAction="" style="document" />
			<wsdl:input name="generarODE">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="generarODEResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="obtenerReferencias">
			<soap:operation soapAction="" style="document" />
			<wsdl:input name="obtenerReferencias">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="obtenerReferenciasResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="WSESTServiceImplService">
		<wsdl:port binding="tns:WSESTServiceImplServiceSoapBinding"
			name="WSESTServiceImplPort">
			<soap:address location="http://200.45.17.36:80/lpservices/ws/ESTSServices" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
